### ISSUE TITLE
Doc issues (pedantic) in Overview, User Guide

### ISSUE THREAD

**Issue by giubots** [lukaszmoskwa/i3hub#1]
1. Top bar - the gear icon is not clear, I think it allows to edit some settings, instead it brings to the home page
2. / - remove "the main sections are the:" for clarity
3. / - final paragraph: add a description about "services"
4. /user/login/ - fix typo: operation through the
5. /user/login/ - make MetaService a link because it is not clear what it is
6. /user/users-management/ - "user management (highlight)" ???
7. /user/users-management/ - "filtered by groups (links)" ???
8. /user/users-management/ - "institution. The private groups" remove "The"
9. /user/users-management/ - "that the user also specify their native language" subject-verb mismatch
10. /user/users-management/ - user groups are documented, but what about public groups?
11. /user/users-management/ - filtering is not explained
12. /user/users-management/ - change language in the screenshots
13. /user/users-management/ - what is the green play button next to the users in the screenshot?
14. /user/users-management/ - can I delete user groups?

I suggest running Grammarly on the doc source

**Comment by lukaszmoskwa** [comment]
Great, I added most of them. Point n* 12 is somehow addressed in #11
