### ISSUE TITLE
Quickstart not working on Node.js v17.4.0

### ISSUE THREAD

**Issue by giubots** [lukaszmoskwa/i3hub#3]
OS: Windows 11 10.0.22000
Node.js: 17.4.0

During the quickstart tutorial, running `npm run dev` causes `ERR_OSSL_EVP_UNSUPPORTED` on Node.js v17.4.0
Mentioned here: [stackoverflow](https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported).
Downgrading Node.js to v16.13.2 solves the issue.

Proposed solution: explicitly mention to use Node LTS

**Comment by lukaszmoskwa** [comment]
Added in the documentation the supported and tested versions
