### ISSUE TITLE
New user creation: mandatory fields

### ISSUE THREAD

**Issue by giubots** [lukaszmoskwa/i3hub#5]
Trying to add a user without the necessary data (for example the name) does not display an error and the form is closed.

To reproduce:
- add new user
- write a name
- leave everything else as is
- click on create
The form closes without error but no user is created.

Suggested solution: mark the mandatory fields as such (or display an error message when the form closes without creating a user).

**Comment by giubots** [comment]
Update: toggling on and off the anonymous option activates a check on the name and surname field (but still the form closes even if they are not set)

**Comment by lukaszmoskwa** [comment]
I added * to show that Name and Surname are required. In addition, a toast pops up when the form is not valid. With the anonymous toggle, the user is intended to have name: "Utente" and surname: "Anonimo" (behaviour subject to further change if requirements change)
